Identified language: pt
Transcript: e aí Olá pessoal, sejam bem-vindos a mais um vídeo e hoje eu vou ensinar-vos como fazer esta espada  ...
Identified language: es
Transcript: Precisamente sobre este caso, el diario estadounidense New York Times reveló este sábado un conjunto ...
Identified language: sl
Transcript: Ni lepška, kaj videl tega otroka v mrekoj svojga okolja, da mu je uspil in to v takimi miri, da pač  ...
Identified language: en
Transcript: Runner's knee runner's knee is a condition characterized by pain behind or around the kneecap. It is ...
