"exceptions":
  - "LeMUR"
  - "Topic Detection"
  - "Sentiment Analysis"
  - "Entity Detection"
  - "PII Redaction"
  - "Speaker Diarization"
  - "Speech-to-Text"
  - "Content Moderation"
  - "Key Phrases"
  - "Auto Chapters"
  - "Speech Understanding"
  - "SRT"
  - "VTT"
  - "Best"
  - "Nano"
  - "SDK"
  - "CLI"
  - "API"
  - "AssemblyAI"
  - "CDN"
  - "Deno"
  - "Bun"
  - "CloudFlare Workers"
  - "LangChain"
  - "Go"
  - "Python"
  - "TypeScript"
  - "Java"
  - "Ruby"
  - "C#"
  - "Q&A"
  - "NVIDIA"
  - "Google Drive"
  - "Google Docs"
  - "Google Translate"
  - "DeepL"
  - "AWS IAM"
"extends": "capitalization"
"level": "warning"
"match": "$sentence"
"message": |
  Use sentence-style capitalization for '%s'.
"scope": "heading"
