extends: substitution
message: When linking in Markdown, use '%s' instead of '%s'.
level: error
ignorecase: false
action:
  name: replace
scope: raw
swap:
  "Check out \\[": "See ["
  "Refer to \\[": "See ["
  "check out \\[": "see ["
  "refer to \\[": "see ["
