"action":
  "name": "replace"
"extends": "substitution"
"ignorecase": false
"level": "warning"
"message": "Use '%s' instead of '%s'."
"swap":
  "websocket": "WebSocket"
  "Websocket": "WebSocket"
  "realtime": "real-time"
  "Realtime": "Real-time"
