extends: ["spectral:oas", "spectral:asyncapi"]
overrides:
  - files:
    - "openapi.yml#/components/schemas/TranscriptParams/example"
    - "openapi.yml#/components/schemas/TranscriptList/example"
    - "openapi.yml#/components/schemas/LemurSummaryResponse/example"
    - "openapi.yml#/components/schemas/LemurSummaryParams/example"
    - "openapi.yml#/components/schemas/LemurQuestionAnswerResponse/example"
    - "openapi.yml#/components/schemas/LemurQuestionAnswerParams/example"
    - "openapi.yml#/components/schemas/LemurActionItemsResponse/example"
    - "openapi.yml#/components/schemas/LemurActionItemsParams/example"
    - "openapi.yml#/components/schemas/LemurTaskParams/example"
    - "openapi.yml#/components/schemas/LemurTaskResponse/example"
    - "asyncapi.yml#/components/schemas/PartialTranscript/examples"
    - "asyncapi.yml#/components/schemas/FinalTranscript/examples"
    rules:
      oas3-valid-schema-example: "off"
      asyncapi-payload-examples: "off"
      asyncapi-schema-examples: "off"
