extends: ["spectral:oas", "spectral:asyncapi"]
overrides:
  - files:
    - "openapi.yml"
    - "asyncapi.yml"
    rules:
      oas3-valid-media-example: "off"
      oas3-valid-schema-example: "off"
      asyncapi-payload-examples: "off"
      asyncapi-schema-examples: "off"
