extends: ["spectral:oas", "spectral:asyncapi"]
overrides:
  - files:
    - "openapi.yml#/components/schemas/TranscriptParams/example"
    - "openapi.yml#/components/schemas/TranscriptList/example"
    - "asyncapi.yml#/components/schemas/PartialTranscript/examples"
    - "asyncapi.yml#/components/schemas/FinalTranscript/examples"
    rules:
      oas3-valid-schema-example: "off"
      asyncapi-payload-examples: "off"
      asyncapi-schema-examples: "off"
