info:
  version: 2.0.0

x-fern-groups:
  transcript:
    summary: Transcript
  lemur:
    summary: LeMUR
  realtime:
    summary: Streaming

components:
  schemas:
    LemurTaskResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurTaskResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false
    LemurSummaryResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurSummaryResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false

    LemurActionItemsResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurActionItemsResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false

    ApiError:
      x-label: Error
      type: object
      additionalProperties: false
      required: [error]
      properties:
        error:
          x-label: Error message
          description: Error message
          type: string
        status:
          x-label: Status
          type: string
          const: error
      example: { error: "format_text must be a Boolean" }

  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"
    NotFound:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"
    TooManyRequests:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"
      headers:
        Retry-After:
          description: The number of seconds to wait before retrying the request
          schema:
            type: integer
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiError"
