default-group: local
async-api: ../asyncapi.yml
openapi: ../openapi.yml
groups:
  local:
    generators:
      - name: fernapi/fern-postman
        version: 0.0.46
        output:
          location: local-file-system
          path: ../postman
  publish:
    generators:
      - name: fernapi/fern-java-sdk
        version: 0.5.18
        output:
          location: maven
          coordinate: com.assemblyai:assemblyai-java
          username: ${MAVEN_USERNAME}
          password: ${MAVEN_PASSWORD}
        github:
          repository: AssemblyAI/assemblyai-java-sdk
          mode: pull-request
        config:
          enable-forward-compatible-enums: true
          client-class-name: AssemblyAI
          custom-dependencies:
            - "implementation javax.websocket:javax.websocket-api:1.1"
