default-group: local
openapi: ../openapi.yml
async-api: ../asyncapi.yml
groups:
  local: 
    generators: 
      - name: fernapi/fern-typescript-node-sdk
        version: 0.7.4-rc0
        output:
          location: npm
          url: npm.buildwithfern.com
          package-name: '@assemblyai-fern/api'
        config:
          namespaceExport: AssemblyAI
          outputSourceFiles: true
  publish:
    generators:
      - name: fernapi/fern-java-sdk
        version: 0.5.14
        output:
          location: maven
          coordinate: com.assemblyai:assemblyai-java
          username: ${MAVEN_USERNAME}
          password: ${MAVEN_PASSWORD}
        github:
          repository: AssemblyAI/assemblyai-java-sdk
          mode: pull-request
        config: 
          enable-forward-compatible-enums: true
          client-class-name: AssemblyAI
          custom-dependencies: 
            - "implementation javax.websocket:javax.websocket-api:1.1"
