x-fern-groups:
  transcripts:
    summary: Transcripts
  lemur:
    summary: LeMUR
  streaming:
    summary: Streaming
components:
  schemas:
    Transcript:
      properties:
        language_code:
          $ref: "#/components/schemas/TranscriptLanguageCode"
    TranscriptOptionalParams:
      properties:
        language_code:
          oneOf:
            - $ref: "#/components/schemas/TranscriptLanguageCode"
            - type: "null"
    LemurBaseParams:
      properties:
        final_model:
          $ref: "#/components/schemas/LemurModel"
