x-fern-groups:
  transcript:
    summary: Transcript
  lemur:
    summary: LeMUR
  realtime:
    summary: Streaming
components:
  schemas:
    Transcript:
      properties:
        language_code:
          $ref: "#/components/schemas/TranscriptLanguageCode"
    TranscriptOptionalParams:
      properties:
        language_code:
          oneOf:
            - $ref: "#/components/schemas/TranscriptLanguageCode"
            - type: "null"
    LemurBaseParams:
      properties:
        final_model:
          $ref: "#/components/schemas/LemurModel"
    LemurTaskResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurTaskResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false
    LemurSummaryResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurSummaryResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false

    LemurActionItemsResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurActionItemsResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false
