x-fern-groups:
  transcript:
    summary: Transcript
  lemur:
    summary: LeMUR
  realtime:
    summary: Streaming

paths:
  /v2/upload:
    post:
      x-fern-examples:
        - code-samples:
            - sdk: curl
              code: |
                curl -X POST https://api.assemblyai.com/v2/upload \
                     -H "Authorization: <apiKey>" \
                     -H "Content-Type: application/octet-stream" \
                     --data-binary @path/to/file

  /v2/transcript/{transcript_id}:
    delete:
      x-fern-examples:
        - path-parameters:
            transcript_id: "{transcript_id}"
          response:
            body:
              {
                id: "47b95ba5-8889-44d8-bc80-5de38306e582",
                language_model: "assemblyai_default",
                acoustic_model: "assemblyai_default",
                language_code: null,
                status: "completed",
                audio_url: "http://deleted_by_user",
                text: "Deleted by user.",
                words: null,
                utterances: null,
                confidence: null,
                audio_duration: 390,
                punctuate: null,
                format_text: null,
                dual_channel: null,
                webhook_url: "http://deleted_by_user",
                webhook_status_code: null,
                webhook_auth: false,
                webhook_auth_header_name: null,
                speed_boost: null,
                auto_highlights_result: null,
                auto_highlights: false,
                audio_start_from: null,
                audio_end_at: null,
                word_boost: null,
                boost_param: null,
                filter_profanity: null,
                redact_pii: false,
                redact_pii_audio: null,
                redact_pii_audio_quality: null,
                redact_pii_policies: null,
                redact_pii_sub: null,
                speaker_labels: null,
                speaker_count: null,
                error: null,
                content_safety: null,
                iab_categories: null,
                content_safety_labels: null,
                iab_categories_result: null,
                language_detection: null,
                custom_spelling: null,
                cluster_id: null,
                throttled: null,
                auto_chapters: false,
                summarization: false,
                summary_type: null,
                summary_model: null,
                custom_topics: null,
                topics: null,
                speech_threshold: null,
                speech_model: null,
                chapters: null,
                disfluencies: true,
                entity_detection: false,
                entities: null,
                speakers_expected: null,
                summary: null,
                sentiment_analysis: false,
                sentiment_analysis_results: null,
              }

components:
  schemas:
    Transcript:
      properties:
        language_code:
          $ref: "#/components/schemas/TranscriptLanguageCode"
    TranscriptOptionalParams:
      properties:
        language_code:
          oneOf:
            - $ref: "#/components/schemas/TranscriptLanguageCode"
            - type: "null"
    LemurBaseParams:
      properties:
        final_model:
          $ref: "#/components/schemas/LemurModel"
    LemurTaskResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurTaskResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false
    LemurSummaryResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurSummaryResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false

    LemurActionItemsResponse:
      allOf:
        - $ref: "#/components/schemas/LemurStringResponse"
        # required to force Fern to keep the LemurActionItemsResponse class around and not use LemurStringResponse directly
        - type: object
          additionalProperties: false
