components:
  securitySchemes:
    ApiKey:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LemurBaseParams:
      properties:
        final_model:
          $ref: "#/components/schemas/LemurModel"
