name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Convert specs to JSON
        run: pnpm run to-json

      - name: Format files
        run: pnpm run format

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::error::Code formatting issues detected. Please run 'pnpm run precommit' locally and commit the changes."
            echo "The following files need formatting:"
            git status --porcelain
            git diff
            exit 1
          else
            echo "All files are properly formatted."
          fi

      - uses: errata-ai/vale-action@v2.1.1

  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Fern
        run: npm install -g fern-api

      - name: Check Fern API is valid
        run: fern check
