name: pr

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: errata-ai/vale-action@v2.1.1
        with:
          version: 3.9.6
