name: Generate Ruby SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Java SDK that you would like to generate"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Release Ruby SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          fern generate --group ruby-sdk --version ${{ inputs.version }} --log-level debug
